version: '3'

x-logging-opts: &x-logging-opts
  logging:
    driver: 'json-file'
    options:
      max-size: '20M'
      max-file: '5'

services:

  gitea:
    <<: *x-logging-opts
    build:
      context: gitea
      args:
        GITEA_VERSION: ${GITEA_VERSION:-latest}
    container_name: gitea
    hostname: gitea
    networks:
      - denver
    ports:
      - '3000:3000/tcp'
      - '2222:22/tcp'
    volumes:
      - ./_gitea_data:/data:rw
    restart: always

networks:
  denver:
    name: denver
